// Catálogo ficticio — nombres genéricos, sin marcas reales.
// Países usados como categoría genérica de geografía. Clubes son nombres de fantasía.

window.PRODUCTS = [
  {
    id: "ARG-86-H",
    name: "Argentina · Mundial '86",
    subtitle: "Albiceleste · Local",
    country: "Argentina",
    type: "Selección",
    era: "Retro",
    version: "Local",
    year: 1986,
    price: 89000,
    palette: ["#FFFFFF", "#74ACDF"],
    badge: "El Diez",
    description: "Réplica del clásico bastón celeste y blanco. Cuello en V tejido, escudo bordado a mano.",
  },
  {
    id: "ARG-86-A",
    name: "Argentina · Mundial '86",
    subtitle: "Albiceleste · Visitante",
    country: "Argentina",
    type: "Selección",
    era: "Retro",
    version: "Visitante",
    year: 1986,
    price: 92000,
    palette: ["#0A2A5E", "#74ACDF"],
    badge: "La Mano",
    description: "Versión azul oscuro de aquel verano mexicano. Tela de algodón pesado, corte clásico.",
  },
  {
    id: "ARG-94-H",
    name: "Argentina · USA '94",
    subtitle: "Albiceleste · Local",
    country: "Argentina",
    type: "Selección",
    era: "Retro",
    version: "Local",
    year: 1994,
    price: 78000,
    palette: ["#FFFFFF", "#74ACDF"],
    description: "Polera con vivos amarillos. Brevísima — duró un partido y medio en la historia.",
  },
  {
    id: "ARG-26-H",
    name: "Argentina · Tres Estrellas",
    subtitle: "Albiceleste · Local",
    country: "Argentina",
    type: "Selección",
    era: "Actual",
    version: "Local",
    year: 2026,
    price: 110000,
    palette: ["#FFFFFF", "#74ACDF"],
    badge: "★★★",
    description: "Edición tres estrellas. Tela técnica de microfibra, costura láser.",
  },
  {
    id: "ARG-26-A",
    name: "Argentina · Tres Estrellas",
    subtitle: "Albiceleste · Visitante",
    country: "Argentina",
    type: "Selección",
    era: "Actual",
    version: "Visitante",
    year: 2026,
    price: 110000,
    palette: ["#0A2A5E", "#F6B40E"],
    description: "Azul profundo con detalles dorados. Para visitar y volver con los tres puntos.",
  },
  {
    id: "ITA-90-H",
    name: "Notti Magiche",
    subtitle: "Italia '90 · Local",
    country: "Italia",
    type: "Selección",
    era: "Retro",
    version: "Local",
    year: 1990,
    price: 95000,
    palette: ["#0A2A5E", "#FFFFFF"],
    description: "Azzurro con brillo. La camiseta de aquel verano italiano que todos recordamos.",
  },
  {
    id: "RIB-87-H",
    name: "La Ribera FC · '87",
    subtitle: "Azul y Oro · Local",
    country: "Argentina",
    type: "Club",
    era: "Retro",
    version: "Local",
    year: 1987,
    price: 84000,
    palette: ["#0A2A5E", "#F6B40E"],
    badge: "10",
    description: "El amarillo y azul que marcó una época. Algodón pesado, número estampado al calor.",
  },
  {
    id: "RIB-26-H",
    name: "La Ribera FC · 2026",
    subtitle: "Azul y Oro · Local",
    country: "Argentina",
    type: "Club",
    era: "Actual",
    version: "Local",
    year: 2026,
    price: 95000,
    palette: ["#0A2A5E", "#F6B40E"],
    description: "Versión moderna del clásico bostero. Tela respirable, escudo termoadherido.",
  },
  {
    id: "RIB-26-T",
    name: "La Ribera FC · 2026",
    subtitle: "Azul y Oro · Tercera",
    country: "Argentina",
    type: "Club",
    era: "Actual",
    version: "Tercera",
    year: 2026,
    price: 99000,
    palette: ["#0E1116", "#F6B40E"],
    description: "Edición negra alternativa con ribetes oro. Para la noche de copa.",
  },
  {
    id: "NAP-87-H",
    name: "Partenope · '87",
    subtitle: "Celeste del Sur · Local",
    country: "Italia",
    type: "Club",
    era: "Retro",
    version: "Local",
    year: 1987,
    price: 105000,
    palette: ["#74ACDF", "#FFFFFF"],
    badge: "Scudetto",
    description: "Celeste mediterráneo con cuello blanco. La camiseta del primer scudetto del sur.",
  },
  {
    id: "NAP-90-H",
    name: "Partenope · '90",
    subtitle: "Celeste del Sur · Local",
    country: "Italia",
    type: "Club",
    era: "Retro",
    version: "Local",
    year: 1990,
    price: 108000,
    palette: ["#74ACDF", "#FFFFFF"],
    description: "Segunda estrella, bordada al pecho. Tela vintage 100% algodón.",
  },
  {
    id: "BAR-82-H",
    name: "Cataluña FC · '82",
    subtitle: "Blaugrana · Local",
    country: "España",
    type: "Club",
    era: "Retro",
    version: "Local",
    year: 1982,
    price: 88000,
    palette: ["#0A2A5E", "#74ACDF"],
    description: "Bastones azules, edición de aquel breve paso por la liga ibérica.",
  },
  {
    id: "ENG-86-A",
    name: "Inglaterra · Visitante",
    subtitle: "Three Lions · Visitante",
    country: "Inglaterra",
    type: "Selección",
    era: "Retro",
    version: "Visitante",
    year: 1986,
    price: 75000,
    palette: ["#74ACDF", "#FFFFFF"],
    description: "Celeste pálido. Una camiseta cargada de historia para los coleccionistas.",
  },
  {
    id: "BRA-86-H",
    name: "Brasil · México '86",
    subtitle: "Verdeamarela · Local",
    country: "Brasil",
    type: "Selección",
    era: "Retro",
    version: "Local",
    year: 1986,
    price: 79000,
    palette: ["#F6B40E", "#0A2A5E"],
    description: "El amarillo canarinho clásico, con cuello redondo y escudo bordado.",
  },
];

window.SIZES = ["S", "M", "L", "XL"];
window.COUNTRIES = ["Argentina", "Italia", "España", "Inglaterra", "Brasil"];
window.TYPES = ["Selección", "Club"];
window.ERAS = ["Retro", "Actual"];
window.VERSIONS = ["Local", "Visitante", "Tercera"];

window.formatPrice = (n) =>
  "$" + n.toLocaleString("es-AR", { maximumFractionDigits: 0 });
